export { About } from './About/About';
export { Blogs } from './Blogs/Blogs';
export  {Blog  } from './Blog/Blog';
export { Footer  } from './Footer/Footer';
export { Hero  } from './Hero/Hero';
export { Jobs  } from './Jobs/Jobs';
export { Layout  } from './Layout/Layout';
export { Links  } from './Links/Links';
export { Navbar  } from './Navbar/Navbar';
export { Project  } from './Project/Project';
export { Projects  } from './Projects/Projects';
export { SEO  } from './SEO/SEO';
export { Sidebar  } from './Sidebar/Sidebar';
export { Socials  } from './Socials/Socials';
export { Title  } from './Title/Title';
export { Particlesbg } from './Particles/Particlesbg';
export { Quotes } from './Quotes/Quotes';